### ISSUE TITLE
Config instance has no attribute 'network'

### ISSUE THREAD

**Issue by shuuchen** [yhenon/keras-frcnn#107]
Hi All,

I downloaded the h5 and pickle file to test. 
Some exception happened as follows:

Using TensorFlow backend.
config.pickle
Traceback (most recent call last):
  File "test_frcnn.py", line 40, in <module>
    if C.network == 'resnet50':
AttributeError: Config instance has no attribute 'network'

**Comment by yhenon** [comment]
This is indeed a bug, I'll get a fix tomorrow. For now a workaround is to
hard code the value C.network='resnet50'

On Jul 16, 2017 10:28 PM, "scdu" <notifications@github.com> wrote:

Hi All,

I downloaded the h5 and pickle file to test.
Some exception happened as follows:

Using TensorFlow backend.
config.pickle
Traceback (most recent call last):
File "test_frcnn.py", line 40, in
if C.network == 'resnet50':
AttributeError: Config instance has no attribute 'network'

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/yhenon/keras-frcnn/issues/107>, or mute the thread

**Comment by shuuchen** [comment]
Thank you!
I did that and it runs well.
