### ISSUE TITLE
Resource exhausted: OOM when allocating tensor with shape[1,38,264,1024]

### ISSUE THREAD

**Issue by rajats920** [yhenon/keras-frcnn#16]
While training the model on VOCdataset I get the following error:

```
`I tensorflow/core/common_runtime/bfc_allocator.cc:700] Sum Total of in-use chunks: 5.15GiB
I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats: 
Limit:                  5601361920
InUse:                  5526863616
MaxInUse:               5601360896
NumAllocs:                44106912
MaxAllocSize:           4623515904

W tensorflow/core/common_runtime/bfc_allocator.cc:274] ****************************************************************************************************

W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 39.19MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[1,38,264,1024]
Traceback (most recent call last):
  File "train_frcnn.py", line 101, in <module>
    max_q_size=1, workers=1)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1877, in fit_generator
    class_weight=class_weight)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1621, in train_on_batch
    outputs = self.train_function(ins)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2103, in __call__
    feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1,38,264,1024]
	 [[Node: gradients/roi_pooling_conv_1/strided_slice_178_grad/StridedSliceGrad = StridedSliceGrad[Index=DT_INT32, T=DT_FLOAT, _class=["loc:@roi_pooling_conv_1/strided_slice_178"], begin_mask=9, ellipsis_mask=0, end_mask=9, new_axis_mask=0, shrink_axis_mask=0, _device="/job:localhost/replica:0/task:0/gpu:0"](gradients/roi_pooling_conv_1/strided_slice_178_grad/Shape, roi_pooling_conv_1/strided_slice_178/stack, roi_pooling_conv_1/strided_slice_178/stack_1, roi_pooling_conv_1/strided_slice_178/stack_2, gradients/roi_pooling_conv_1/Reshape_56_grad/Reshape)]]

```
How can we introduce batches to avoid this error in train_frcnn.py?
P.S. I have a GTX 1060 6GB card on ubuntu 16.04

**Comment by yhenon** [comment]
Hi,
Thanks for your report. Could you please share your setting for image size (found in config.py, should be 600 if unchanged) and num_rois? These make a big difference in terms of memory usage, especially num_rois.

**Comment by rajats920** [comment]
`self.im_size = 600`
 `self.num_rois = 2`

I tried training with `num_rois=1` but it still gives the same error.
The model trains for about 15% epochs but then it stops with the above error.

**Comment by sholsapp** [comment]
I'm getting the same error.

```
self.im_size = 300
self.num_rois = 1
```

Using this GPU:

```
  Chipset Model:	NVIDIA GeForce GT 650M
  VRAM (Total):	1024 MB
```

**Comment by yungs2017** [comment]
I have the same error, I solve it at last, the following may help you.

> Be careful not to run the evaluation and training binary on the same GPU or else you might run out of memory. Consider running the evaluation on a separate GPU if available or suspending the training binary while running the evaluation on the same GPU.

**Comment by ianyourdaddy** [comment]
so how would i evaluate how many gpu memory i need for train and for evaluation

**Comment by Abhijit-2592** [comment]
@yhenon  if we change the default image size from 600 to something else say like 400 shouldn't we change the rpn_stride accordingly? I am a bit confused about it
