### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\in0131\\Downloads\\data(1)\\VOCtrainval_06-Nov-2007\\VOCdevkit\\VOC2012\\Annotations'

### ISSUE THREAD

**Issue by ManjeeraJagiri** [yhenon/keras-frcnn#163]
When I run the following command on windows command prompt:
```
C:\Users\in0131\Downloads\keras-frcnn-master\keras-frcnn-master>python train_frcnn.py -p C:\Users\in0131\Downloads\data(1)\VOCtrainval_06-Nov-2007\VOCdevkit\
```
I receive the following error:
```
Using TensorFlow backend.
Parsing annotation files
[Errno 2] No such file or directory: 'C:\\Users\\in0131\\Downloads\\data(1)\\VOCtrainval_06-Nov-2007\\VOCdevkit\\VOC2007\\ImageSets\\Main\\test.txt'
[Errno 2] No such file or directory: 'C:\\Users\\in0131\\Downloads\\data(1)\\VOCtrainval_06-Nov-2007\\VOCdevkit\\VOC2012\\ImageSets\\Main\\trainval.txt'
Traceback (most recent call last):
  File "train_frcnn.py", line 79, in <module>
    all_imgs, classes_count, class_mapping = get_data(options.train_path)
  File "C:\Users\in0131\Downloads\keras-frcnn-master\keras-frcnn-master\keras_frcnn\pascal_voc_parser.py", line 46, in get_data
    annots = [os.path.join(annot_path, s) for s in os.listdir(annot_path)]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\in0131\\Downloads\\data(1)\\VOCtrainval_06-Nov-2007\\VOCdevkit\\VOC2012\\Annotations'
```
Any help is appreciated!

**Comment by rodrigo2019** [comment]
download both VOC, 2007 and 2012, inside in your path must have VOC2012 and VOC2007 folder

**Comment by ManjeeraJagiri** [comment]
@rodrigo2019 Thanks a lot for your reply!. So after adding VOC2012 and VOC2007 in the path. I ran the following command 
```C:\Users\in0131\Downloads\keras-frcnn-master\keras-frcnn-master>python train_frcnn.py -p C:\Users\in0131\Downloads\keras-frcnn-master\keras-frcnn-master```

I get the following error ```[Errno 2] No such file or directory: 'C:\\Users\\in0131\\Downloads\\keras-frcnn-master\\keras-frcnn-master\\VOC2007\\ImageSets\\Main\\test.txt'```, I assuming the code searches for the non existent file test.txt instead of trainval.txt in VOC2007. But why does it do so? And also what does it mean by the TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations?/

```Using TensorFlow backend.
Parsing annotation files
[Errno 2] No such file or directory: 'C:\\Users\\in0131\\Downloads\\keras-frcnn-master\\keras-frcnn-master\\VOC2007\\ImageSets\\Main\\test.txt'
Training images per class:
{'aeroplane': 1333,
 'bg': 0,
 'bicycle': 1255,
 'bird': 1870,
 'boat': 1457,
 'bottle': 2195,
 'bus': 957,
 'car': 4136,
 'cat': 1666,
 'chair': 4488,
 'cow': 1127,
 'diningtable': 1110,
 'dog': 2136,
 'horse': 1209,
 'motorbike': 1191,
 'person': 22848,
 'pottedplant': 1827,
 'sheep': 1437,
 'sofa': 1266,
 'train': 1032,
 'tvmonitor': 1260}
Num classes (including bg) = 21
Config has been written to config.pickle, and can be loaded when testing to ensure correct results
Num train samples 22136
Num val samples 0
loading weights from resnet50_weights_tf_dim_ordering_tf_kernels.h5
2017-09-04 12:56:43.127184: W d:\build\tensorflow\tensorflow-r1.2\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-09-04 12:56:43.127347: W d:\build\tensorflow\tensorflow-r1.2\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-04 12:56:43.128836: W d:\build\tensorflow\tensorflow-r1.2\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-04 12:56:43.129359: W d:\build\tensorflow\tensorflow-r1.2\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-04 12:56:43.130050: W d:\build\tensorflow\tensorflow-r1.2\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-04 12:56:43.130589: W d:\build\tensorflow\tensorflow-r1.2\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Starting training
Epoch 1/2000
1/1 [==============================] - 73s - rpn_cls: 1.0588 - rpn_regr: 0.0887 - detector_cls: 3.0445 - detector_regr: 0.5246```

**Comment by rodrigo2019** [comment]
I don't knowm why the code look for that files, I use the simple parser for my own dataset, so I dont know much about the VOC parser.
About the tensorflow, I get the same warning, but I don't know what is the meaning. But if you build the tensorflow from the source the warning will disappear and you will get a little bit more performance.

**Comment by ManjeeraJagiri** [comment]
@rodrigo2019 , Oh okay will try that. Thanks a lot!

**Comment by lifei1229** [comment]
@ManjeeraJagiri  i met the same problems, it shows [Errno 2] No such file or directory: 'C:\\Users\\in0131\\Downloads\\keras-frcnn-master\\keras-frcnn-master\\VOC2007\\ImageSets\\Main\\test.txt' . And how did you do？

**Comment by ManjeeraJagiri** [comment]
@lifei1229 , It starts training despite this error. I assume, by default it looks for this txt file but it actually doesn't require it when it is training.

**Comment by lifei1229** [comment]
thank u, when i run the test_frcnn.py , I receive the following error:

``  File "test_frcnn.py", line 136, in <module>
    model_rpn.load_weights(C.model_path, by_name=True)
  File "D:\Users\lifei\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\topology.py", line 2613, in load_weights
    f = h5py.File(filepath, mode='r')
  File "D:\Users\lifei\Anaconda3\envs\tensorflow\lib\site-packages\h5py\_hl\files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "D:\Users\lifei\Anaconda3\envs\tensorflow\lib\site-packages\h5py\_hl\files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = './model_frcnn.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```
how should i do?
