### ISSUE TITLE
No such file or directory: '.../VOCdevkit/VOC2007/Annotations' in 2012 dataset

### ISSUE THREAD

**Issue by piotrkochan** [yhenon/keras-frcnn#192]
```
╭─user@user-pc /media/sdb1/dev/learn/keras-frcnn  ‹master› 
╰─$ ls -l python train_frcnn.py --path=/home/machinelearning/datasets/VOCdevkit/
4 drwxrwxrwx 7 kochan kochan 4096 maj 11  2012 VOC2012
╭─user@user-pc /media/sdb1/dev/learn/keras-frcnn  ‹master› 
╰─$ python train_frcnn.py --path=/home/machinelearning/datasets/VOCdevkit/        
Using TensorFlow backend.
Parsing annotation files
[Errno 2] No such file or directory: '/home/machinelearning/datasets/VOCdevkit/VOC2007/ImageSets/Main/trainval.txt'
[Errno 2] No such file or directory: '/home/machinelearning/datasets/VOCdevkit/VOC2007/ImageSets/Main/test.txt'
Traceback (most recent call last):
  File "train_frcnn.py", line 79, in <module>
    all_imgs, classes_count, class_mapping = get_data(options.train_path)
  File "/media/sdb1/dev/learn/keras-frcnn/keras_frcnn/pascal_voc_parser.py", line 46, in get_data
    annots = [os.path.join(annot_path, s) for s in os.listdir(annot_path)]
FileNotFoundError: [Errno 2] No such file or directory: '/home/machinelearning/datasets/VOCdevkit/VOC2007/Annotations
```

**Comment by bluelight773** [comment]
Not sure if there may be unintended consequences to this, but I got around the error by editing pascal_voc_parser.py as to replace:
` ['VOC2007', 'VOC2012']`
with
` ['VOC2012']`

FWIW, after 96 epochs (resnet50) where only VOC2012 is used, I get a model that at least seems to somewhat work for person detection though it didn't seem to work well for other objects.

**Comment by yyeboah** [comment]
The combined capacity of ['VOC2007', 'VOC2012'] = 22136 training images, giving your model a better chance at generalization(assuming everything else is in place). Removing 'VOC2007' simply deprives your model of the additional training data (5011 images to be specific). To train on both datasets, download them into `/path/to/pascalvoc/` as `VOC2007` and `VOC2012`.
