### ISSUE TITLE
custom data training. 

### ISSUE THREAD

**Issue by burnmyletters** [yhenon/keras-frcnn#20]
While training the model on custom dataset I get the following error:

```
Starting training
Epoch 1/100
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 606, in data_generator_task
    generator_output = next(self._generator)
  File "/mnt/md0/igor/noaasl/keras-frcnn/keras_frcnn/data_generators.py", line 601, in get_anchor_gt
    all_img_data = sorted(all_img_data)
TypeError: unorderable types: dict() < dict()

Traceback (most recent call last):
  File "train_frcnn.py", line 114, in <module>
    max_q_size=1, workers=1)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1852, in fit_generator
    str(generator_output))
ValueError: output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: None
```

```
>>> k.__version__
'2.0.3'
>>> tf.__version__
'1.1.0-rc2'
```

Thank You,
Igor

**Comment by yhenon** [comment]
This is a python3 issue - could you try using python2?

**Comment by burnmyletters** [comment]
Thank you! It did the trick.

**Comment by wanjinchang** [comment]
burnmyletters,how did you solve the problem??I got the same probelm with you.

**Comment by burnmyletters** [comment]
try to perform the training with python2.7

**Comment by wanjinchang** [comment]
I cannot understand the effect of the function of all_img_data = sorted(all_img_data),could you solve it for me?Thank you

**Comment by yhenon** [comment]
It ensures that data is iterated over in a deterministic manner, which is
useful for reproducible results. Feel free to change the line on your side.

**Comment by wanjinchang** [comment]
Thank you for your reply!!Because my environment is bulid on python3.5,which integrate keras2.0 and tensorflow,so I donnot want to used to python2.x.I try to comment the code all_img_data = sorted(all_img_data),but when I train the model,it stop at Epoch 1/100,and didnot continue!
