### ISSUE TITLE
trained hdf5 and pickle files

### ISSUE THREAD

**Issue by kOC94** [yhenon/keras-frcnn#23]
Hello,
does anyone have fully trained hdf5 and pickle files? I would really like to test this network for my bachelor thesis.
Thanks a lot!

**Comment by yhenon** [comment]
I am hoping to release TF weights in the next 2-3 days. No plan on theano weights.

**Comment by kOC94** [comment]
TF weights would be great! Thanks for your quick reply.

**Comment by Xiaomi2008** [comment]
how can I get/generate config.pickle file?

**Comment by kOC94** [comment]
As far as I understood, these files are generated when you run the train_frcnn.py.

**Comment by Xiaomi2008** [comment]
thanks, it works now

**Comment by kOC94** [comment]
Did you train this network successfully on pascal voc? It would be amazing then, if you could upload the .pickle and .hdf5 files.

**Comment by Xiaomi2008** [comment]
Still in training, I will  upload those file once it is done

**Comment by kOC94** [comment]
Thank you, I will test them in the next days and give you some feedback, if it is working for me!

**Comment by Crul** [comment]
Hi, I'm playing with this repository. It looks great, thanks.

I tried the google drive model and it works fine!
Thanks again.

**Comment by Crul** [comment]
I've executed the measure_map (with the google drive's model) over some images of Pascal VOC and it works great (only a minor problem with nan values in the log).

But, in pascal_voc_parser.py, I had to move the test_files.append(...) to another try block because if the attempt of loading the trainval file failed, the test loading was not executed.

Compare the following code with the current version:
https://github.com/yhenon/keras-frcnn/blob/master/keras_frcnn/pascal_voc_parser.py#L28-L36
```
    try:
        with open(imgsets_path_trainval) as f:
            for line in f:
                trainval_files.append(line.strip() + '.jpg')
    except Exception as e:
        print(e)
    
    try:
        with open(imgsets_path_test) as f:
            for line in f:
                test_files.append(line.strip() + '.jpg')
    except Exception as e:
        print(e)
```

**Comment by yhenon** [comment]
Thanks for your feedback @Crul . Glad to hear it works for you! Good call on changing the structure of the try bock. Will commit it soon.

**Comment by kOC94** [comment]
Hello yhenon, I tried your weights on some pictures with horses in riding school with a big perspective distortion. Often it detects horses as dogs and misses some horses. I will try to expand training especially in regard to horses and test your network again and let you know my results.

**Comment by yhenon** [comment]
The model is trained on pascal voc images and should be tested on similar images. There is no expectation that it should generalise well to a very different dataset. You'll need to retrain the model a bit or remove the distortion.

**Comment by kOC94** [comment]
Yeah, that is what I have thought of before. But as I am new to NN I hoped that I could get acceptable results without retraining the model. So thanks for your advices!

**Comment by kOC94** [comment]
Hi, I wanted to report, that I retrained your weights with just 400 pictures and got really good results! It probably just needs some fine tuning to solve my problem completely.

**Comment by sholsapp** [comment]
Can you share the exact commands you used to train the model/config file on the Google Drive link? I'm having a tough time reproducing the model. While the model from Google Drive works fine, a model that I train myself does not work.

**Comment by sameerg07** [comment]
hi, @kOC94 ,
 Can you share the code how you trained it again for yuor model , because i wanted to add a class for bags which i am not able to do so. :|

**Comment by kOC94** [comment]
@sameerg07 @sholsapp : Sorry for my late reply, I was very busy working on my bachelor thesis in the last months. For training I used the exact same command as yhenon wrote in the README file:
**python2 train_frcnn.py --input_weight_path /path/to/model_frcnn.hdf5 -p /path/to/VOC/**

With "--input_weight_path" you can specify the path to the weights which should be loaded to initialize your model. Luckily I never had problems loading the resnet weights. At one point I just had problems loading the model_frcnn.hdf5 from Google Drive, as I changed the ratio and size of the anchor boxes. So maybe you could check whether you changed something in code? If not, I am not sure what else could cause this problem.
@sameerg07 : If you want to add some classes you will just have to annotate pictures with these classes and train the model from Google Drive on them like I explained above. But I am not sure if your trained model would then still predict the other classes or just bags ... maybe you will have to provide every class you want the model to predict later in training pictures.

**Comment by yellowjs0304** [comment]
Hi, I am using your code . It is awesome . But, I don't have any time for training. 
I downloaded the weights in google-drive from your comment.
I just changed the file in my directory but, when i run test_frcnn.py, it returns error.

Traceback (most recent call last):
  File "test_frcnn.py", line 38, in <module>
    if C.network == 'resnet50':
AttributeError: Config instance has no attribute 'network'

How can I fix this error?

**Comment by shkval25** [comment]
Hi all,
is there any trained weights from vgg16 using pascal VOC dataset? I've tried some from keras but I always get the "Could not load pretrained model weights" error. I have no issues loading resnet50 trained weights though.

thank you very much

**Comment by alexcnwy** [comment]
@yhenon thanks for all your hard work - this is really great project :) 

I just wanted to ask how to *fine-tune* your weights - if I use the `input_weight_path` argument, it seems to be re-training from scratch. Also, would this work if I added or removed classes or would I have to then train from scratch? Could you please give some ballpark on how many training examples are needed - say for a single class would I need 10/100/100/10k annotated examples?

Thanks again!

**Comment by bhargavaurala** [comment]
@yhenon I tried to test the model uploaded on drive on VOC2012 images. I was not able to get the config.pickle because google drive would gave me a 404 page when I hit the download link. So I generated my own config.pickle by training for a few epochs. The labels are consistently wrong with high confidence. I assume this is because of mismatch in the class_mapping of the pretrained model and the ones I generated. Could you please reupload the right config.pickle so that I can verify the trained weights?

Thanks!

**Comment by yhenon** [comment]
I'll check my google drive, thanks for the report

**Comment by cholaxz** [comment]
@yellowjs0304 Maybe you solved it already.

Check it here.
https://github.com/yhenon/keras-frcnn/issues/107

**Comment by eldor4do** [comment]
Hi, is it possible to use these weights to fine tune them for a different class? Something like retraining the final layer of Inception model?

**Comment by Mhttx2016** [comment]
thanks for your wonderful trained weights, it works very good. I try to retrain from the trained weights(with input_weight_path=model_frcnn.hdf5) on voc2007 and 2012, after 4k iteration(epoch length 1000 and 4 epochs), i test with the new weights, and the result gets worse :(, can you tell me the training detail, such as the epoch length, number of epochs and the learning rate, and the losses and the end of the training.

**Comment by Mhttx2016** [comment]
@yhenon thanks for your wonderful trained weights, it works very good. I try to retrain from the trained weights(with input_weight_path=model_frcnn.hdf5) on voc2007 and 2012, after 4k iteration(epoch length 1000 and 4 epochs), i test with the new weights, and the result gets worse :(, can you tell me the training detail, such as the epoch length, number of epochs and the learning rate, and the losses and the end of the training.

**Comment by Mhttx2016** [comment]
@yhenon thanks for your wonderful trained weights, it works very well. I try to retrain from the trained weights(with input_weight_path=model_frcnn.hdf5) on voc2007 and voc2012, after 4k iterations(epoch length 1000 and 4 epochs), i test with the new weights, and the result gets worse :(, can you tell me the training detail, such as the epoch length, number of epochs and the learning rate, and the losses at the end of the training.

**Comment by ChengZY** [comment]
Thanks for your code. I have a problem when I use the pretrained_models in google-drive.
I run test_frcnn.py, it returns an error.  I noticed #107 but I still have no idea how to solve it.

File "test_frcnn.py", line 38, in <module>
    if C.network == 'resnet50':
AttributeError: 'Config' object has no attribute 'network' .

**Comment by ferakon** [comment]
@ChengZY just add: C.network = 'resnet50' before the if statement in test_frcnn.py as a workaround.

**Comment by ChengZY** [comment]
@ferakon Thanks, it works

**Comment by ferakon** [comment]
@ChengZY no problem!

**Comment by EhudEilon** [comment]
I'm trying to run the trained google drive weights on some random test images from the internet and get the following error:
"This application failed to start because it could not find or load the Qt platform plugin "windows"
in ""."
The code runs, prints some console output, but does not finishes.
Is it because of faulty installation of the project on my part? I've just downloaded the files and ran them after despairing of finding any relevant working installation instructions from github for windows. I'm running it with tensorflow on a windows 10 laptop.

**Comment by eeilon79** [comment]
Tried a brute force solution and failed.
I've installed Qt creator (community edition 4.4.1). 
Found a platforms directory. Copied all files from there to the keras-fcrnn directory, in particular qwindows.dll. Closed and reopened command prompt. Ran the same test syntax (python test_frcnn.py -p C:\keras-frcnn\test_images).
Got the same error message.
Frustrating.

**Comment by eeilon79** [comment]
Well, for some reason it works on my desktop. So nevermind.

**Comment by mrqorib** [comment]
@yhenon Thank you for your great work! I just want to ask, the pretrained weights that you provided, is it trained on ImageNet like the one mentioned in paper? Or is it something else? Thanks!

**Comment by sxhlvye** [comment]
@mrqorib You can get answers from the comments  of yhenon above, the time is about May 8, 2017.
He mentioned "The model is trained on pascal voc images and should be tested on similar images".
