### ISSUE TITLE
Try VGG16 as base model

### ISSUE THREAD

**Issue by mattdingmeng** [yhenon/keras-frcnn#56]
@yhenon I am trying to use VGG16 as the base model, since the training is too slow (10 days for 1000 epoch) using the current Resnet50. In the function nn_base(), I changed to a VGG16 model wrote in Keras. I did not change the other layers (rpn, classifier). However, when the training was start, the error came out like this:

Exception: Incompatible shapes: [1,16,22,36] vs. [1,4,5,36]
	 [[Node: sub_2 = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](strided_slice_4, rpn_out_regress/BiasAdd)]]
	 [[Node: Mean_5/_157 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1555_Mean_5", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Do you know where should I change if I would like to use the VGG model?
Thanks!

**Comment by jahdiel** [comment]
I would also like to know @yhenon

**Comment by Ahleroy** [comment]
Hello @mattdingmeng , did you succeeded to implement the VGG16 ?

I quickly tried to reproduce what you say and I have the following error :

> Traceback (most recent call last):
  File "train_frcnn.py", line 114, in <module>
    rpn = nn.rpn(shared_layers, num_anchors)
  File "\keras_frcnn\resnet.py", line 202, in rpn
    x = Convolution2D(512, (3, 3), padding='same', activation='relu', kernel_ini
tializer='normal', name='rpn_conv1')(base_layers)
  File "\site-packages\keras\engine\topology.py", line 541, in __call__
    self.assert_input_compatibility(inputs)
  File "\site-packages\keras\engine\topology.py", line 435, in assert_input_compatibility
    if K.ndim(x) != spec.ndim:
  File "\site-packages\keras\backend\tensorflow_backend.py", line 479, in ndim
    dims = x.get_shape()._dims
AttributeError: 'Model' object has no attribute 'get_shape'

Do you have this kind of error with the new version of the script ?

Regards,

**Comment by yhenon** [comment]
I'm working on this btw - not that much more complex to use vgg, although I dont know how the memory is affected.

**Comment by Ahleroy** [comment]
Hello, 

I am currently working on this issue. I made a first PR in order to all get the same code in #86 . 

Please, update the code if you succeed to resolve the issue :)

**Comment by USTClj** [comment]
@mattdingmeng  Hi~ Have you solved the problem ‘Exception: Incompatible shapes: [1,16,22,36] vs. [1,4,5,36]’ ? 
I'm trying another base network and meet a similar mistake. 
Could you please give a hint what caused your problem?
Thank you.

**Comment by mattdingmeng** [comment]
Not yet. I did not solved it.
