### ISSUE TITLE
train Faster Rcnn on Blood microscopic Image to Recognize WBC -- Purple Color Cell 

### ISSUE THREAD

**Issue by akshaylamba** [yhenon/keras-frcnn#77]
![bloodimage_00011](https://user-images.githubusercontent.com/19161823/27464070-eb6f8a32-57e8-11e7-8f4c-44d6f5d945f9.jpg)

Below is the Annotation File ```
```

<annotation verified="no">
  <folder>Original_Images</folder>
  <filename>BloodImage_00011</filename>
  <path>/Users/cosmic/wbc-classification/Original_Images/BloodImage_00011.jpg</path>
  <source>
    <database>Unknown</database>
  </source>
  <size>
    <width>640</width>
    <height>480</height>
    <depth>3</depth>
  </size>
  <segmented>0</segmented>
  <object>
    <name>Neutrophil</name>
    <pose>Unspecified</pose>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <bndbox>
      <xmin>89</xmin>
      <ymin>104</ymin>
      <xmax>309</xmax>
      <ymax>339</ymax>
    </bndbox>
  </object>
</annotation>
```

What Do U Suggest ....

I Think Resnet Shall not Be Helpful ...So How Can I Use a Model with faster RCNN..

```

**Comment by yhenon** [comment]
I think resnet would work very nicely here. Have you tried it ? You'll just need to convert your annotation files.

**Comment by akshaylamba** [comment]
yes I have Started Training the network with my blood image with annotation as above..

training would Take a Long Time ....

**Comment by akshaylamba** [comment]
Loading Resnet in train_frcnn.py with below code ( Using Tensorflow)
```


print("--------------------------------------------------------------------------")
print('loading weights from {}'.format(C.base_net_weights))
print("--------------------------------------------------------------------------")
model_rpn.load_weights("/home/ubuntu/notebooks/keras-frcnn/weights/resnet50_weights_th_dim_ordering_th_kernels_notop.h5")
model_classifier.load_weights("/home/ubuntu/notebooks/keras-frcnn/weights/resnet50_weights_th_dim_ordering_th_kernels_notop.h5")
print("--------------------------------------------------------------------------")
print('Weights Loaded Successfully ')
print("--------------------------------------------------------------------------")

```
Error Message >>>
```

Traceback (most recent call last):
  File "train_frcnn.py", line 132, in <module>
    model_rpn.load_weights("/home/ubuntu/notebooks/keras-frcnn/weights/resnet50_weights_th_dim_ordering_th_kernels_notop.h5")
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2482, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2868, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 106 layers into a model with 89 layers.


```

**Comment by yhenon** [comment]
You changed the code, it should be `load_weights('xxxx', by_name=True)`
