### ISSUE TITLE
KeyError: 'difficult'

### ISSUE THREAD

**Issue by USTClj** [yhenon/keras-frcnn#81]
When I run measure-map.py,  I met with this error:

Elapsed time = 1.20761704445
Traceback (most recent call last):
  File "measure_map.py", line 268, in <module>
    t, p = get_map(all_dets, img_data['bboxes'], (fx, fy))
  File "measure_map.py", line 65, in get_map
    if not gt_box['bbox_matched'] and not gt_box['difficult']:
KeyError: 'difficult'

I don't know how to fix it

**Comment by yhenon** [comment]
this is indeed a bug - thanks for pointing it out. Pascal voc has `difficult` annotations but other datasets dont.
